#!/bin/bash
#ln -s /home/b32804/pub_workspace/github/dotfiles/.gitconfig   ~/.gitconfig  
#ln -s /home/b32804/pub_workspace/github/dotfiles/.Xdefaults   ~/.Xdefaults  
#ln -s /home/b32804/pub_workspace/github/dotfiles/.Xresources  ~/.Xresources 
#ln -s /home/b32804/pub_workspace/github/dotfiles/.emacs       ~/.emacs
#ln -s /home/b32804/pub_workspace/github/dotfiles/.vimrc       ~/.vimrc

pwd=`pwd`
for i in `find . -name '.*'`
do
	if [ ! -d $i ]; then
		if [ `basename $i` == ".emacs" ]; then
			continue
		fi
		if [ `basename $i` == ".Xdefaults" ]; then
			continue
		fi
		if [ `basename $i` == ".Xresources" ]; then
			continue
		fi
		if [ `basename $i` == ".bashrc" ]; then
            lnk_name=.mybashrc
            echo "if [ -f ~/$lnk_name ]; then" >> ~/.bashrc
            echo "    . ~/$lnk_name ]" >> ~/.bashrc
            echo "fi" >> ~/.bashrc
        else
            lnk_name=`basename $i`
		fi
        if [ -f $HOME/$lnk_name ]; then
            echo "$HOME/$lnk_name already exists, skip"
            continue
        fi
		echo ls -s $pwd/`basename $i` $HOME/$lnk_name
		ln -s $pwd/`basename $i` $HOME/$lnk_name
	fi
done
