;; -*- Emacs-Lisp -*-

(defun my-color-theme-dark ()
  (interactive)
  (color-theme-install
   '(my-color-theme-dark
      ((background-color . "#101e2e")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#0d4519"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-function-name-face ((t (:foreground "#edd400"))))
     (font-lock-keyword-face ((t (:foreground "#729fcf"))))
     (font-lock-string-face ((t (:foreground "#ad7fa8"))))
     (font-lock-type-face ((t (:foreground"#8ae234"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))

(defun my-color-theme-ps-color ()
  (interactive)
  (color-theme-install
   '(my-color-theme-ps-color
      ((background-color . "#030303")
      (background-mode . light)
      (border-color . "#d7cccc")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#d7cccc"))))
     (mode-line ((t (:foreground "#efefef" :background "#484848"))))
     (region ((t (:background "#666666"))))
     (font-lock-builtin-face ((t (:foreground "#ec8ee6"))))
     (font-lock-comment-face ((t (:foreground "#c9b522"))))
     (font-lock-function-name-face ((t (:foreground "#ffffff"))))
     (font-lock-keyword-face ((t (:foreground "#96bbe4"))))
     (font-lock-string-face ((t (:foreground "#e77e91"))))
     (font-lock-type-face ((t (:foreground"#ffffff"))))
     (font-lock-variable-name-face ((t (:foreground "#f0f0ef"))))
     (minibuffer-prompt ((t (:foreground "#bfbfbf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'my-color-theme-ps-color)

;(provide 'my-color-theme-dark)
(require 'color-theme)
(color-theme-initialize)
(my-color-theme-ps-color)