#!/bin/sh

if [ ! -e $1 ]; then
    echo "$1 does not exist."
    exit
fi

hh=`stat -c %y $1 | awk '{print $2}' | awk -F':' '{print $1}'`

if [ -n "$2" ]; then
    if [ $hh -lt $2 ]; then
        echo $1
    fi
fi
