#!/bin/bash
debug=0

function usage()
{
    echo "`basename $0` -f wma_name [-t output_type] [-F] [-k] [-c] [-o output_dir]"
    echo "    output_type: mp3 or m4a"
    echo "    output_dir: output directory"
    echo "    -F: overwrite wav file if exist"
    echo "    -k: keep wav file after processing done"
    echo "    -c: remove orignal file after processing done"
}

force=0
keepsrc=1
keepwav=0
ftype=m4a
while getopts ":f:t:Fkco:" opt
do
    case $opt in
        k)
            keepwav=1
            ;;
        c)
            keepsrc=0
            ;;
        F)
            force=1
            ;;
        f)
            name=$OPTARG 
            ;;
        t)
            ftype=$OPTARG 
            ;;
        o)
            odir=$OPTARG 
            ;;
    esac
done

if [ "$name" == "" ]; then
	echo missing input wma file >&2
    usage
	exit
fi

mplayer_bin=mplayer
if [ "$ftype" == "m4a" ]; then
    tool_bin=faac
elif [ "$ftype" == "mp3" ]; then
    tool_bin=lame
else
    echo "Unsupported file type: $ftype" >&2
    usage
    exit
fi

if [ ! `which $mplayer_bin` ]; then
    no_mplayer=1
    echo "$mplayer_bin is not found." >&2
fi

if [ ! `which $tool_bin` ]; then
    no_tool=1
    echo "$tool_bin is not found." >&2
fi

if [ $no_mplayer ] || [ $no_tool ]; then
    usage
    exit
fi

odir=`readlink -f $odir`
if [ ! -d $odir ]; then
    if [ $debug -eq 1 ];then
        echo "create directory $odir"
    else
        mkdir $odir
    fi
fi

fname=$(basename "$name")
extname="${name##*.}"
fname="${name%.*}"

if [ -z "$odir" ]; then
    dname=`dirname $name`
    dname=`cd $dname; pwd`
else
    dname=$odir
fi

year=`dirname $name`
year=`basename $year`
srcfile=$name
wavfile=/tmp/${fname}.wav
outfile=$dname/${fname}.$ftype

if ( [ -f "${wavfile}" ] && [ $force ] ) || [ ! -f "${wavfile}" ]; then
    if [ $debug -eq 1 ];then
        echo $mplayer_bin "$srcfile" -ao pcm:file="${wavfile}"
    else
        $mplayer_bin "$srcfile" -ao pcm:file="${wavfile}"
    fi
fi

infofile=$dname/../info
if [ -e "$infofile" ]; then
	album=`grep album "$infofile"| awk -F "=" '{print $2}'| sed 's/\s*$//g' `
	artist=`grep artist "$infofile"| awk -F "=" '{print $2}'| sed 's/\s*$//g' `
	genre=`grep genre "$infofile"| awk -F "=" '{print $2}'| sed 's/\s*$//g' `
	artwork=`grep artwork "$infofile"| awk -F "=" '{print $2}'| sed 's/\s*$//g' `

    if [ "$ftype" == "mp3" ]; then
        option="-V 0 --id3v2-only --quiet --tt \"${year}_${fname}\" --ty \"${year}\""
        if [ -n "$album" ]; then
            option="$option --tl \"$album\""
        fi
        if [ -n "$artist" ]; then
            option="$option --ta \"$artist\""
        fi
        if [ -n "$genre" ]; then
            option="$option --tg \"$genre\""
        fi
        if [ -n "$artwork" ] && [ -e "$artwork" ]; then
            option="$option --ti \"$artwork\""
        fi
    elif [ "$ftype" == "m4a" ]; then
        option="-q 300 --title \"${year}_${fname}\" --year \"${year}\""
        if [ -n "$album" ]; then
            option="$option --album \"$album\""
        fi
        if [ -n "$artist" ]; then
            option="$option --artist \"$artist\""
        fi
        if [ -n "$genre" ]; then
            option="$option --genre \"$genre\""
        fi
        if [ -n "$artwork" ] && [ -e "$artwork" ]; then
            option="$option --cover-art \"$artwork\""
        fi

    fi
fi

if [ "$ftype" == "mp3" ]; then
    if [ $debug -eq 1 ];then
        echo $tool_bin $option "${wavfile}" "$outfile"
    else
        bash -c "$tool_bin $option \"${wavfile}\" \"$outfile\""
    fi
elif [ "$ftype" == "m4a" ]; then
    if [ $debug -eq 1 ];then
        echo $tool_bin $option "${wavfile}" -o "$outfile"
    else
        bash -c "$tool_bin $option \"${wavfile}\" -o \"${outfile}\""
    fi
fi

if [ -e "${outfile}" ]; then
    if [ $keepsrc -eq 0 ] && [ -e "${srcfile}" ]; then
        if [ $debug -eq 1 ]; then
            echo rm "${srcfile}"
        else
            echo rm "${srcfile}"
            `rm "${srcfile}"`
        fi
    fi
    if [ $keepwav -eq 0 ] && [ -e "${wavfile}" ]; then
        if [ $debug -eq 1 ]; then
            echo rm "${wavfile}"
        else
            echo rm "${wavfile}"
            `rm "${wavfile}"`
        fi
    fi
fi
