#!/bin/bash

LNX=~/workshop/linux/
CSHOME=~/cscope

find  $LNX -path "$LNX/arch/*" ! -path "$LNX/arch/arm*" -prune -o -path "$LNX/include/asm-*" ! -path "$LNX/include/asm-arm*" -prune -o -path "$LNX/tmp*" -prune -o -path "$LNX/Documentation*" -prune -o -path "$LNX/scripts*" -prune -o -path "$LNX/drivers*" -prune -o -name "*.[chxsS]" -print >$CSHOME/cscope.files

cd $CSHOME
cscope -b -q -k 
if [ -f cscope.out ]; then
	mv cscope.* $LNX
fi
