#!/bin/bash
if [ ! $# -eq 1 ];then
	echo missing input wma file 
	exit
elif [ ! -e $1 ];then
	echo \"$1\" doesn not exist
	exit
fi

extname=`echo $1 | awk -F . '{if (NF > 1) print $NF}'`
fname=`basename $1 .$extname`
dname=`dirname $1`
dname=`cd $dname; pwd`
year=`basename $dname`

mplayer "$1" -ao pcm:file="$dname/${fname}.wav"

# sox split and join wav file
sox "$dname/${fname}.wav" "$dname/${fname}_part1.wav" 5:00 24:05
sox "$dname/${fname}.wav" "$dname/${fname}_part2.wav" 29:05 24:05
sox "$dname/${fname}.wav" "$dname/${fname}_part3.wav" 61:05 24:05

option="--tt \"${year}_${fname}\" --ty \"${year}\""
if [ -e "$dname/../.info" ]; then
	album=`grep album "$dname/../.info"| awk -F "=" '{print $2}'| sed 's/\s*$//g' `
	artist=`grep artist "$dname/../.info"| awk -F "=" '{print $2}'| sed 's/\s*$//g' `
	gene=`grep gene "$dname/../.info"| awk -F "=" '{print $2}'| sed 's/\s*$//g' `
	artwork=`grep artwork "$dname/../.info"| awk -F "=" '{print $2}'| sed 's/\s*$//g' `

	if [ -n "$album" ]; then
		option="$option --tl \"$album\""
	fi
	if [ -n "$artist" ]; then
		option="$option --ta \"$artist\""
	fi
	if [ -n "$gene" ]; then
		option="$option --tg \"$gene\""
	fi
	if [ -n "$artwork" ] && [ -e "$artwork" ]; then
		option="$option --ti \"$artwork\""
	fi
fi

echo lame -V 0 --id3v2-only $option "$dname/${fname}.wav" "$dname/${fname}.mp3"
bash -c "lame -V 0 --id3v2-only --quiet $option \"$dname/${fname}.wav\" \"$dname/${fname}.mp3\""

if [ -e "$dname/${fname}.mp3" ];then
	rm "$dname/${fname}.wma" "$dname/${fname}.wav"
fi
